### ISSUE TITLE
Should use os.path.join for portability

### ISSUE THREAD

**Issue by agamdua** [abrignoni/iLEAPP#10]
This was done for ALEAPP in https://github.com/abrignoni/ALEAPP/pull/2/

Should also be done here.

(Created as a public todo, anyone is welcome to pickup the work)

**Comment by abrignoni** [comment]
Will start working on this.

**Comment by agamdua** [comment]
Nice! Probably worth merging #14 and pulling from that before you do, after this we shouldn't have too many _huge_ changes.
