### ISSUE TITLE
Longitude not consistently spelled, knowCall throws errors

### ISSUE THREAD

**Issue by threeplanetssoftware** [abrignoni/iLEAPP#111]
Running the current version of iLEAPP against test data which has knowledgeC information in it leads to this error:

``` python
Incepted bplist extractions in KnowledgeC.db completed
Reading KnowledgeC artifact had errors!
Error was 'Longitude'
Exception Traceback: Traceback (most recent call last):
  File "/home/notta/data/programming/python/iLEAPP/scripts/ilap_artifacts.py", line 406, in process_artifact
    method(files_found, report_folder, seeker)
  File "/home/notta/data/programming/python/iLEAPP/scripts/artifacts/knowCall.py", line 1443, in get_knowCall
    kmlgen(report_folder, kmlactivity, data_list, data_headers)
  File "/home/notta/data/programming/python/iLEAPP/scripts/ilapfuncs.py", line 194, in kmlgen
    lon = modifiedDict['Longitude']
KeyError: 'Longitude'
```

It appears the root cause is in the following line wherein the data headers specify 'Logitude' as the field name, not 'Longitude'. This leads to the `keyError`. My preferred fix would be to fix the spelling in the below line back to 'Longitude' as that is the name used in the original database, but the choice is yours. 

https://github.com/abrignoni/iLEAPP/blob/68c08a19d2eac05759a5d891fcd2b1194afe2870/scripts/artifacts/knowClocation.py#L91

Because I believe the exported TSV already had ingest artifacts written for it for other tools, I've made a change to just check for 'Logitude', instead of changing the data headers to 'Longitude'. PR with the fix is incoming.

**Comment by abrignoni** [comment]
The way the function works is that it looks for the headers named
Timestamp, Latitude, and Longitude to use for the KML file generation.
The fix should be changing the misspelled data header (my fault) to the
correct spelling. Hopefully my spelling mistake was in just that one place.

**Comment by threeplanetssoftware** [comment]
I only saw it in the one place when i grepped, so that should fix it.

**Comment by threeplanetssoftware** [comment]
Believe this issue can be closed.
