### ISSUE TITLE
Add a debug mode which doesn't swallow exceptions

### ISSUE THREAD

**Issue by agamdua** [abrignoni/iLEAPP#12]
Usually when debugging, one will just observe a message like this in the execution logs:

```
Error in Aggregated dictionary Distribution Keys section.
```

But it swallows the actual exception. This is good for user experience, but not necessarily good for development experience.

The ability to see where the process bombed would be helpful, instead of having to run it with a debugger the next round.

**Comment by abrignoni** [comment]
https://github.com/abrignoni/ALEAPP/blob/c221d7cd70be299c8eb4d2afa1a36a3aeb4446b4/scripts/ilap_artifacts.py#L55-L61

Error handling by @ydkhatri on ALEAPP. I think it serves the purpose.
Thoughts?

**Comment by agamdua** [comment]
I should have mentioned this but at the moment it's only used in the `aggregated_dictionary` module, but I introduced some error handling by adding a decorator which has an advantage of not hindering user experience since it requires one to use the debug flag.

I am yet to document it, but it can be found here https://github.com/abrignoni/iLEAPP/blob/657dcf9081fc9a97c20a4ba1ba035c4e2a3fc983/contrib/utils.py#L9-L24

It is pretty easy to use, just decorate the function you want to use it with:

https://github.com/abrignoni/iLEAPP/blob/657dcf9081fc9a97c20a4ba1ba035c4e2a3fc983/contrib/aggregated_dictionary/main.py#L23-L26

And you can pass in any `category` you want to get the output, and you can change `log_template` too:

https://github.com/abrignoni/iLEAPP/blob/657dcf9081fc9a97c20a4ba1ba035c4e2a3fc983/contrib/aggregated_dictionary/main.py#L67-L72

I am actually thinking of pulling this out as a library since I have used the pattern before and would like to again and I don't want to keep re-writing it and having better docs and tests for it can't hurt.

The error handling in that diff is not bad, but I don't like performing a `str(ex)` as that also swallows data, specifically what exception it is and the whole traceback.

Here is an example:

```python
# simple handling
In [1]: def hello():
   ...:     try:
   ...:         1/0
   ...:     except Exception as e:
   ...:         print(str(e))
   ...:
In [2]: hello()
division by zero
```

```python
# handling with more verbosity
In [4]: def hello():
   ...:     try:
   ...:         1/0
   ...:     except Exception as e:
   ...:         logging.exception("Find the full exception below")
   ...:
   ...:

In [5]: hello()
ERROR:root:Find the full exception below
Traceback (most recent call last):
  File "<ipython-input-4-f84727c464bc>", line 3, in hello
    1/0
ZeroDivisionError: division by zero
```

I'd like to leave this issue open though because it has not been ported to be used across other modules.

**Comment by agamdua** [comment]
(There are improvements I want to make to how I am using `logging` here, I am using the default and it can be made much better with proper loggingConfig)
