### ISSUE TITLE
Make slightly faster by merging modules that operate on the same file(s)

### ISSUE THREAD

**Issue by ydkhatri** [abrignoni/iLEAPP#164]
Regex on the root directory listing is one of the slowest to execute (especially when input is folder), but it has to execute once per module listing. There are many modules that operate on the same file(s). These can be merged into a single module, to reduce the loop iterations and make this faster. For example:
```
'aggDictpasscode': ('Aggregate Dictionary', '*/AggregateDictionary/ADDataStore.sqlitedb'),
'aggDictpasscodetype': ('Aggregate Dictionary', '*/AggregateDictionary/ADDataStore.sqlitedb'),
'cloudkitNoteSharing': ('Cloudkit', '*NoteStore.sqlite*'),
'cloudkitParticipants': ('Cloudkit', '*NoteStore.sqlite*'),
'safariHistory': ('Safari Browser', '**/Safari/History.db'),
'safariWebsearch': ('Safari Browser', '**/Safari/History.db'),
```
There are few others too.

**Comment by ydkhatri** [comment]
#165 is for the same too

**Comment by threeplanetssoftware** [comment]
I took a peek at this issue and the only file that looked to still be offending in the list above was my notes code. The PR listed should fix that issue.
