### ISSUE TITLE
Move HTML out of python functions into jinja2

### ISSUE THREAD

**Issue by agamdua** [abrignoni/iLEAPP#20]
This has been done successfully in the `aggregated_dictionary` module:

https://github.com/abrignoni/iLEAPP/blob/master/contrib/aggregated_dictionary/main.py#L23-L35

https://github.com/abrignoni/iLEAPP/blob/master/contrib/aggregated_dictionary/html/passcode_type.html

Should be done in the others too.

**Comment by abrignoni** [comment]
Reviewing the code. Trying to get my head around it. If I understand correctly the category of the artifact goes from ilapfuncs to a directory in contrib which holds the main for the code and sql for the query. Correct?

I would need to create the proper contrib directories-main-sql as necessary and import into ilapfuncs. Right?

**Comment by agamdua** [comment]
Yep, you have it down.

What I would recommend is taking a shot at https://github.com/abrignoni/iLEAPP/blob/master/contrib/system_diagnosis/main.py#L26-L199 first.

In this case all one would need to do is create the HTML file under an `html/` using `jinja2` since the rest is done.
