### ISSUE TITLE
Requirements failure

### ISSUE THREAD

**Issue by jijames** [abrignoni/iLEAPP#256]
On a fresh install of Ubuntu with Python 3.10 installed. Clone iLEAPP main.

`pip3 install -r requirements.txt`

Resulted in: 

`ERROR: Could not find a version that satisfies the requirement python-magic-bin (from versions: none)
ERROR: No matching distribution found for python-magic-bin`

Package "python-magic" was installed via pip3. Seems to work instead of python-magic-bin.

**Comment by abrignoni** [comment]
There are some issues with some in libraries Python 3.10. The current
requirements.txt should work with Python 3.9. I think we will need to check
if the current libraries (to include python - magic as you identified) work
on 3.10 on Mac and windows as well.

**Comment by jijames** [comment]
I'll try to test on Windows and let you know.

**Comment by jarlethorsen** [comment]
Apparently there are no linux version of python-magic-bin available at pypi:
https://pypi.org/project/python-magic-bin/#files

Using the package python-magic instead will probably work just as fine.

**Comment by jijames** [comment]
Confirmed that python-magic is working. Consider moving python-magic-bin references to python-magic.

**Comment by abrignoni** [comment]
Send me a pull request if you can so your name can be part of the contributors in the repo. 🙂
