### ISSUE TITLE
iLEAPP GUI Error in Latest Commit

### ISSUE THREAD

**Issue by chipriley** [abrignoni/iLEAPP#27]
I receiving the following error when attempting to analyze a GrayKey full filesystem extraction with the latest commits.  I ran an analysis a couple of days ago with a previous version and it completed without error.  Here's the traceback:

```python traceback
Traceback (most recent call last):
  File "ileappGUI.py", line 115, in <module>
    extract_and_process(pathto, extracttype, tosearch, log, gui_window=window)
  File "[redacted]\extraction.py", line 71, in extract_and_process
    process_file_found(filefound, key, val, log, gui_window)
  File "[redacted]\extraction.py", line 127, in process_file_found
    globals()[key](filefound)
  File "[redacted]\ilapfuncs.py", line 1124, in mib
    file = open(filename, "r", encoding="utf8")
FileNotFoundError: [Errno 2] No such file or directory: '\\private\\var\\installd\\Library\\Logs\\MobileInstallation\\moile_installation.log.0'
```
Not sure if something changed but it shuts down the GUI and stops parsing.

**Comment by abrignoni** [comment]
Fixing now

**Comment by abrignoni** [comment]
Issue at os.path.join() at search_file.py.
Fixed applied. Will leave open as marker to follow up with a more efficient solution soon.

**Comment by chipriley** [comment]
That fixed it.  

On a possibly related note (but it might need to be a separate issue), I just tried the latest committed version against a GrayKey BFU extraction and got the following traceback error:

``` python traceback
Traceback (most recent call last):
  File "ileappGUI.py", line 115, in <module>
    extract_and_process(pathto, extracttype, tosearch, log, gui_window=window)
  File "[redacted]\iLEAPP\extraction.py", line 71, in extract_and_process
    process_file_found(filefound, key, val, log, gui_window)
  File "[redacted]\iLEAPP\extraction.py", line 127, in process_file_found
    globals()[key](filefound)
  File "[redacted]\iLEAPP\ilapfuncs.py", line 294, in knowledgec
    """
sqlite3.OperationalError: no such table: ZSTRUCTUREDMETADATA
```
I'm guessing that the absence of something in the BFU extraction is causing it to crash.

**Comment by abrignoni** [comment]
Fixing now.

**Comment by abrignoni** [comment]
Put some try except clauses around the KnowledgeC artifacts so the program won't crash.
There might be more needed. Thanks for testing on a BFU extraction @chipriley. I will get one tomorrow so i can do more testing and fixes.

**Comment by abrignoni** [comment]
Fix has been tested and merged. 
Will be working on BFU extractions too moving forward.

**Comment by chipriley** [comment]
Just had the opportunity to run it again with the latest commits against the same BFU extraction.  Got another crash:

```python traceback
Traceback (most recent call last):
  File "ileappGUI.py", line 115, in <module>
    extract_and_process(pathto, extracttype, tosearch, log, gui_window=window)
  File "[redacted]\iLEAPP\extraction.py", line 71, in extract_and_process            process_file_found(filefound, key, val, log, gui_window)
  File "[redacted]\iLEAPP\extraction.py", line 127, in process_file_found            globals()[key](filefound)
  File "[redacted]\iLEAPP\ilapfuncs.py", line 2513, in calhist
    FROM ZCALLRECORD """
sqlite3.OperationalError: no such table: ZCALLRECORD
```
Want me to open a new issue, @abrignoni ?

**Comment by abrignoni** [comment]
Yes please. Will work on it. 👍

**Comment by abrignoni** [comment]
Those are interesting errors @chipriley.
It seems that the script finds/extracts the databases but they are missing tables, which makes no sense.
What iOS version is the BFU?
Can you share the Script Logs from the run?
I should have a BFU to test soon as well.

**Comment by chipriley** [comment]
The issue is probably because the GrayKey generates zero byte files with metadata of the original file (all available in a BFU file system) when the file is still encrypted.

**Comment by abrignoni** [comment]
Oh I see. That's it. Good. Thanks for the info.
I just need to wrap all artifact code in try except clauses. Will do so in the coming days.
Will eventually refactor so that it adds the clauses it calls the functions. Less duplication of code in the artifacts.
