### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by upintheairsheep** [abrignoni/iLEAPP#276]
*Chrome tabs data and tab image cache
*Chrome recently closed
*Chrome bookmarks
*Chrome Famicons
*Chrome reading list
*GMail cache
*Google drive, docs, sheets, and slides downloaded data
*Jailbreak status
*Google login
*Minecraft World thumbnails
*Minecraft Text (signs, name tag, book, etc)

**Comment by upintheairsheep** [comment]
-

**Comment by abrignoni** [comment]
Closing these request threads. They became long "parse every app ever invented without the requester providing any coding support or sample data to assist" threads. Totally useless.
