### ISSUE TITLE
Tar/zip copy of iOS device

### ISSUE THREAD

**Issue by wb4r** [abrignoni/iLEAPP#312]
Hi

This is less of an issue and more of a n00b question - so apologies ahead.

iLEAPP GUI doesn't recognise my iPad via USB when I browse to add files/directories. I imagine this is the intended way. 

**So any pointers to how do I make a tar/zip copy of my device so I can extract it via scp to my computer and throw it at iLEAPP?** 

Thanks in advance

**Comment by wb4r** [comment]
I used this repo https://github.com/RealityNet/ios_triage

Happy to know if there are alternatives.

Thanks

**Comment by abrignoni** [comment]
The following link has a small section on how to create a full file system extraction from an iOS device using Checkra1n. These type or extractions provide more than the script references previously from compatible devices. 

https://abrignoni.blogspot.com/2019/12/ios-imgur-app-realm-database-example.html?m=1

There are detailed guides on how to use Checkra1n. A quick Google search will find them. 

![Screenshot_20220611-033407.png](https://user-images.githubusercontent.com/28718987/173180431-ed589db5-1527-4431-aa40-d7984d2db938.png)

**Comment by wb4r** [comment]
thank you very much @abrignoni - I'll check it out, I had no clue checkra1n had that capability.
