### ISSUE TITLE
Errors when installing 

### ISSUE THREAD

**Issue by Forgedmom** [abrignoni/iLEAPP#316]
I am getting the following error when I'm setting up iLEAPP. It's happening on all of my computers so I am sure its a user error, but I am so new to this, I have no idea what its saying. Can anyone help, please? 

 Building wheel for astc_decomp (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      C:\Python\lib\site-packages\setuptools\dist.py:717: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
        warnings.warn(
      C:\Python\lib\site-packages\setuptools\dist.py:717: UserWarning: Usage of dash-separated 'long-description' will not be supported in future versions. Please use the underscore name 'long_description' instead
        warnings.warn(
      running bdist_wheel
      running build
      running build_ext
      building 'astc_decomp' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for astc_decomp
  Running setup.py clean for astc_decomp
  Building wheel for pyliblzfse (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [5 lines of output]
      running bdist_wheel
      running build
      running build_ext
      building 'liblzfse' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyliblzfse
  Running setup.py clean for pyliblzfse
Failed to build astc_decomp pyliblzfse
Installing collected packages: pyliblzfse, pyasn1, biplist, astc_decomp, python-dateutil, pathlib2, numpy, nska-deserialize, pandas, cryptography, bs4, PGPy
  Running setup.py install for pyliblzfse ... error
  error: subprocess-exited-with-error

  × Running setup.py install for pyliblzfse did not run successfully.
  │ exit code: 1
  ╰─> [5 lines of output]
      running install
      running build
      running build_ext
      building 'liblzfse' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pyliblzfse

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by abrignoni** [comment]
Have you tried using Python 3.9?

**Comment by jijames** [comment]
@Forgedmom python is trying to build extensions, but it cannot find Microsoft Visual C++ build tools.

* Download and install Microsoft Visual C++ build tools: https://visualstudio.microsoft.com/visual-cpp-build-tools/
* Download and install the newest Python: https://www.python.org/ftp/python/3.10.6/python-3.10.6-amd64.exe
* Download and extract the newest version of iLEAPP: https://github.com/abrignoni/iLEAPP/archive/refs/heads/master.zip
* Open PowerShell (command line window) and change directory to iLEAPP:   cd [where you unzipped ileapp]
* Install requirements:  pip install -r requirements.txt
* (If there is an error, it's probably with C++ build tools not found)
* If everything worked, then you can run iLEAPP:  python ileapp.py -h

**Comment by abrignoni** [comment]
Try using Python 3.9

**Comment by JamesHabben** [comment]
@jijames were you able to resolve this issue?

**Comment by JamesHabben** [comment]
closing. no response.
