### ISSUE TITLE
Cloudkit Participants Script with no Artifact Entry

### ISSUE THREAD

**Issue by jijames** [abrignoni/iLEAPP#322]
Module cloudkitParticipants has no ilap_artifacts entry and does not seem to be referenced anywhere else.
https://github.com/abrignoni/iLEAPP/blob/master/scripts/artifacts/cloudkitParticipants.py

**Comment by abrignoni** [comment]
Look at the first commit on that script. I bet I screwed up at some point and left it out ilap_artifacts. The path and all that's needed is there.

**Comment by jijames** [comment]
No comment.
It looks like it's working on NoteStore.sqlite - the same as "cloudkitSharing"

**Comment by abrignoni** [comment]
It a vestigual script. 😂
It used to be how we loaded the artifacts before we had the loader
function.

BTW I'm updating all the LEAPPs to your new artifact format. It is awesome.

Also planning on adding datetime timezone offsets soon. Do you have
discord? Email me: abrignoni(at)duck.com

**Comment by JamesHabben** [comment]
is this 'issue' not an issue anymore then?

**Comment by JamesHabben** [comment]
@jijames or @abrignoni are the only folks with ability to `close` this i think
