### ISSUE TITLE
Comments in ilap_artifacts.py with no corresponding script

### ISSUE THREAD

**Issue by jijames** [abrignoni/iLEAPP#324]
Recommend for deletion. They don't seem to point to anything anymore.

             'appUpdates':('App Updates', '**/AppUpdates.sqlitedb'),
             'systemVersion':('Device Info', '**/SystemVersion.plist'),

    Artifacts take long to run. Useful in specific situations only.
    'aggDict':('Aggregate Dictionary', '*/AggregateDictionary/ADDataStore.sqlitedb')
  'aggDictScalars':('Aggregate Dictionary', '*/AggregateDictionary/ADDataStore.sqlitedb')

**Comment by JamesHabben** [comment]
Looks like this has been resolved in some way. Closing for now.
