### ISSUE TITLE
Test iTunes backup support with new artifact structure

### ISSUE THREAD

**Issue by jijames** [abrignoni/iLEAPP#332]
After #325 I've tested all dump types except iTunes backup. Someone please confirm it's still working.

**Comment by ClaudioWayne** [comment]
Hi,
just tested iTunes backup
output: 

```
python3 ileapp.py -t itunes -i ~/Desktop/.... -o ~/Desktop/....
Traceback (most recent call last):
  File "ileapp.py", line 214, in <module>
    main()
  File "ileapp.py", line 84, in main
    crunch_artifacts(list(loader.plugins), extracttype, input_path, out_params, 1, wrap_text)
  File "ileapp.py", line 140, in crunch_artifacts
    plugin.method([info_plist_path], out_params.report_folder_base, seeker, wrap_text)
UnboundLocalError: local variable 'plugin' referenced before assignment
```

Systeminfo:
Description:	Ubuntu 20.04.5 LTS
commit ad78cdabc71c6b9fe90f594d2daa760221c62864
Python 3.8.10

Thx for your afford and this great Tool

Claudio Wayne

**Comment by JSulkin** [comment]
Hi!

Amazing work Alexis, just I saw a problem here:

% python3 ileappGUI.py

Traceback (most recent call last):
  File "/Users/***/Desktop/Herramientas/Smartphones/iLEAPP/ileappGUI.py", line 219, in <module>
    crunch_successful = ileapp.crunch_artifacts(
  File "/Users/***/Desktop/Herramientas/Smartphones/iLEAPP/ileapp.py", line 146, in crunch_artifacts
    plugin.method([info_plist_path], out_params.report_folder_base, seeker, wrap_text)
UnboundLocalError: local variable 'plugin' referenced before assignment

Im working on a MAC Monterey...

Best!

**Comment by abrignoni** [comment]
Fixed.
