### ISSUE TITLE
CSV generations in line with HTML

### ISSUE THREAD

**Issue by agamdua** [abrignoni/iLEAPP#35]
Inspired by #34.

Currently CSV generation works by parsing the HTML output. 

Now that we are moving to a model where one function is going to be used for writing an HTML template `write_html_template`, we can make something similar for CSV, and not have the hacky report parsing.

There are two ways to approach this:

1. This is a bit of a refactor because currently, it requires us to change the function signatures of some of the functions of `extraction.py` as well as signal to the artifact parsing function (the `key` field of the dictionary `tosearch` that we have more data than just `filefound`.

I have been thinking of changing the signature of the functions to accept an optional `meta` parameter.

2. An alternative to this would be somewhere we store global state in a file. In this case, we could just write the `CSV Output` dir during the `pre_extract` function, and the artifact parsing function in `contrib` could just check for the presence of that dir and write CSV if so.
I think this is a better solution in the short-term.

Either way, we'd want to get to a point where #13 is done before this is useful.

**Comment by agamdua** [comment]
To this end, the first order of business for me is to rip out the write_html_template function from contrib.aggregate_dictionary to contrib.utils so it can be reused easily.

**Comment by abrignoni** [comment]
I agree. Will continue to move functions out of ileapfuncs and then
properly setting the html and sql scripts for each. Like you said, after
that is done the CSV feature can be redone.
