### ISSUE TITLE
Fatal error detected v1.18.0

### ISSUE THREAD

**Issue by Mistercatapulte** [abrignoni/iLEAPP#383]
Same error with python 3.10 and 3.11, can't finalised the report. Thx

![Capture d’écran 2022-10-26 094416](https://user-images.githubusercontent.com/47787324/197965347-3056eed6-cbee-42f9-85bd-8d9610a951d3.jpg)

**Comment by abrignoni** [comment]
See attached picture from the Readme. ![Screenshot_20221026-071553.png](https://user-images.githubusercontent.com/28718987/198012643-7dd8ad2f-1035-4f61-a376-1a1d0dc05223.png)

**Comment by Mistercatapulte** [comment]
Oh my bad!
