### ISSUE TITLE
No files found for...

### ISSUE THREAD

**Issue by JSulkin** [abrignoni/iLEAPP#387]
Hi Alexis, amazing work!

I cant get the info because it says:

Extraction/Path selected: /Users/j*****/Desktop/1175b82c51eb8e0c31d4e3b2ee6748f96a0d6313

No files found for lastbuild -> *LastBuildInfo.plist

No files found for accs -> **/Accounts3.sqlite

No files found for tileAppDisc -> */private/var/mobile/Containers/Shared/AppGroup/*/com.thetileapp.tile-DiscoveredTileDB.sqlite*

No files found for tileAppNetDb -> */private/var/mobile/Containers/Shared/AppGroup/*/com.thetileapp.tile-TileNetworkDB.sqlite*

No files found for confaccts -> **/com.apple.accounts.exists.plist

No files found for addressbook -> **/AddressBook.sqlitedb*

No files found for airtags -> */Caches/com.apple.findmy.fmipcore/Items.data

No files found for alarms -> *private/var/mobile/Library/Preferences/com.apple.mobiletimerd.plist

No files found for alltrails -> **/Documents/AllTrails.sqlite*

No files found for appconduit -> **/AppConduit.log.*

No files found for tcc -> *TCC.db*

No files found for applepodcasts -> **/MTLibrary.sqlite*

No files found for applewalletpasses -> **/nanopasses.sqlite3*

No files found for applewalletpasses -> **/Cards/*.pkpass/pass.json

No files found for applewallettransactions -> **/passes23.sqlite

No files found for applewalletcards -> */private/var/mobile/Containers/Data/Application/*/Library/Caches/com.apple.Passbook/Cache.db*

No files found for ooklaSpeedtestData -> **/speedtest.sqlite*

No files found for biomeAppinstall -> */Biome/streams/restricted/_DKEvent.App.Install/local/*

No files found for biomeBluetooth -> */Biome/streams/restricted/Device.Wireless.Bluetooth/local/*

No files found for biomeBattperc -> */Biome/streams/restricted/_DKEvent.Device.BatteryPercentage/local/*

No files found for biomeDevplugin -> */Biome/streams/restricted/_DKEvent.Device.IsPluggedIn/local/*

No files found for biomeUseractmeta -> */Biome/streams/restricted/UserActivityMetadata/local*

No files found for biomeCarplayisconnected -> */Biome/streams/restricted/_DKEvent.Carplay.IsConnected/local/*

No files found for biomeSafari -> */Biome/streams/restricted/_DKEvent.Safari.History/local/*

No files found for biomeBacklight -> */Biome/streams/public/Backlight/local/*

No files found for biomeWifi -> */Biome/streams/restricted/_DKEvent.Wifi.Connection/local/*

No files found for biomeNotificationsPub -> */biome/streams/public/Notification/local/*

No files found for biomeHardware -> */Biome/streams/restricted/OSAnalytics.Hardware.Reliability/local/*

No files found for biomeLocationactivity -> */Biome/streams/restricted/_DKEvent.App.LocationActivity/local/*

No files found for biomeInFocus -> */Biome/streams/restricted/_DKEvent.App.InFocus/local/*

No files found for biomeNowplaying -> */Biome/streams/public/NowPlaying/local/*

No files found for biomeNotes -> */Biome/streams/restricted/NotesContent/local/*

No files found for bluetooth -> **/com.apple.MobileBluetooth.*

No files found for bumble -> **/Library/Caches/Chat.sqlite*

No files found for bumble -> **/Documents/yap-database.sqlite*

No files found for calendarall -> **/Calendar.sqlitedb

No files found for callhistory -> **/CallHistory.storedata*

No files found for recentApphistory -> */com.apple.CarPlayApp.plist

No files found for cashapp -> **private/var/mobile/Containers/Shared/AppGroup/*/CCEntitySync-api.squareup.com.sqlite*

No files found for cashapp -> **private/var/mobile/Containers/Shared/AppGroup/*/CCEntitySync-internal.cashappapi.com.sqlite*

No files found for celwireless -> *wireless/Library/Preferences/com.apple.*

No files found for cloudkitparticipants -> *NoteStore.sqlite*

No files found for cloudkitsharing -> *NoteStore.sqlite*

No files found for condev -> **/iTunes_Control/iTunes/iTunesPrefs

No files found for controlcenter -> **private/var/mobile/Library/ControlCenter/ModuleConfiguration.plist

No files found for dhcphp -> **/private/var/db/dhcpd_leases*

No files found for dhcpl -> **/private/var/db/dhcpclient/leases/en*

No files found for discordacct -> */var/mobile/Containers/Data/Application/*/Documents/mmkv/mmkv.default

No files found for discordjson -> */com.hammerandchisel.discord/fsCachedData/*

No files found for discordmanifest -> */private/var/mobile/Containers/Data/Application/*/Documents/RCTAsyncLocalStorage_V1/manifest.json

No files found for draftmessage -> */SMS/Drafts/*/composition.plist

No files found for facebookmessenger -> **/lightspeed-*.db*

No files found for filesappsclient -> *private/var/mobile/Library/Application Support/CloudDocs/session/db/client.db*

No files found for filesAppsm -> *private/var/mobile/Containers/Shared/AppGroup/*/smartfolders.db*

No files found for filesappsdb -> *private/var/mobile/Library/Application Support/CloudDocs/session/db/server.db*

No files found for geodapplications -> **/AP.db*

No files found for geodmaptiles -> **/MapTiles.sqlitedb*

No files found for geodpdplacecache -> **/PDPlaceCache.db*

No files found for mapsSync -> */MapsSync_0.0.1*

No files found for gmail -> **/private/var/mobile/Containers/Data/Application/*/Library/Application Support/data/*/searchsqlitedb*

No files found for gmail -> **/private/var/mobile/Containers/Data/Application/*/Library/Application Support/data/*/sqlitedb*

No files found for googleduo -> */Application Support/DataStore*

No files found for googleduo -> */Application Support/ClipsCache/*.png

No files found for health -> */Health/healthdb_secure.sqlite*

No files found for health -> */Health/healthdb.sqlite*

No files found for quickLook -> */Quick Look/cloudthumbnails.db*

No files found for icloudmeta -> */iclouddrive/Metadata.txt

No files found for aicloudphotometa -> */cloudphotolibrary/Metadata.txt

No files found for icloudSharedalbums -> */private/var/mobile/Media/PhotoData/PhotoCloudSharingData/*

No files found for imoHD_Chat -> **/IMODb2.sqlite*

No files found for imoHD_Chat -> private/var/mobile/Containers/Data/Application/*/Library/Caches/videos/*.webp

No files found for instagramThreads -> */mobile/Containers/Data/Application/*/Library/Application Support/DirectSQLiteDatabase/*.db*

No files found for appgrouplisting -> */Containers/Shared/AppGroup/*/.com.apple.mobile_container_manager.metadata.plist

No files found for appgrouplisting -> **/PluginKitPlugin/*.metadata.plist

No files found for applicationstate -> **/applicationState.db

No files found for applicationsnapshots -> **/Library/Caches/Snapshots/*

No files found for applicationsnapshots -> **/SplashBoard/Snapshots/*

No files found for appitunesmeta -> **/iTunesMetadata.plist

No files found for appitunesmeta -> **/BundleMetadata.plist

No files found for Intents -> */private/var/mobile/Library/Biome/streams/public/AppIntent/local/*

No files found for Intents -> */AppIntent/local/*

No files found for interactionCcontacts -> **/interactionC.db*

No files found for deviceactivator -> *private/var/mobile/Library/Logs/mobileactivationd/ucrt_oob_request.txt

No files found for mailprotect -> **/private/var/mobile/Library/Mail/* Index*

No files found for iconsScreen -> **/SpringBoard/IconState.plist

No files found for webClips -> *WebClips/*.webclip/*

No files found for keyboardLexicon -> */private/var/mobile/Library/Keyboard/*-dynamic.lm/dynamic-lexicon.dat

No files found for keyboardAppUsage -> */private/var/mobile/Library/Keyboard/app_usage_database.plist

No files found for kijijiConversations -> */Library/Caches/conversation_cache

No files found for kikBplistmeta -> */mobile/Containers/Shared/AppGroup/*/cores/private/*/attachments/*

No files found for kikLocaladmin -> */kik.sqlite*

No files found for kikUsersgroups -> */kik.sqlite*

No files found for kikPendingUploads -> */mobile/Containers/Shared/AppGroup/*/cores/private/*/chunked_upload_storage/pending_uploads

No files found for kikPendingUploads -> */mobile/Containers/Shared/AppGroup/*/cores/private/*/chunked_upload_storage/data_cache/*

No files found for kikMessages -> **/kik.sqlite*

No files found for kikMessages -> */mobile/Containers/Shared/AppGroup/*/cores/private/*/content_manager/data_cache/*

No files found for kikGroupadmins -> */kik.sqlite*

No files found for locServicesconfig -> */Library/Preferences/com.apple.locationd.plist

No files found for locServicesconfig -> */Library/Caches/locationd/clients.plist

No files found for locServicesconfig -> */Library/Preferences/com.apple.routined.plist

No files found for tileApp -> *private/var/mobile/Containers/Data/Application/*/Library/log/com.thetileapp.tile*

No files found for weatherAppLocations -> */private/var/mobile/Containers/Shared/AppGroup/*/Library/Preferences/group.com.apple.weather.plist

No files found for applemapsgroup -> **/Shared/AppGroup/*/Library/Preferences/group.com.apple.Maps.plist

No files found for cacheroutesgmap -> **/Library/Application Support/CachedRoutes/*.plist

No files found for tileAppDb -> *private/var/mobile/Containers/Shared/AppGroup/*/com.thetileapp.tile-TileNetworkDB.sqlite*

No files found for applemapssearchhistory -> *private/var/mobile/Containers/Data/Application/*/Library/Maps/GeoHistory.mapsdata

No files found for applemapssearchhistory -> */GeoHistory.mapsdata

No files found for applemapsapplication -> **/Data/Application/*/Library/Preferences/com.apple.Maps.plist

No files found for mediaLibrary -> **/Medialibrary.sqlitedb

No files found for medicalID -> */private/var/mobile/Library/MedicalID/MedicalIDData.archive

No files found for teams -> */var/mobile/Containers/Shared/AppGroup/*/SkypeSpacesDogfood/*/Skype*.sqlite*

No files found for teams -> */var/mobile/Containers/Shared/AppGroup/*/SkypeSpacesDogfood/Downloads/*/Images/*

No files found for teamsSegment -> */var/mobile/Containers/Data/Application/*/Library/DriveIQ/segments/current/*.*

No files found for mobileActivationLogs -> **/mobileactivationd.log*

No files found for mobileBackup -> */Preferences/com.apple.MobileBackup.plist

No files found for mobileContainerManager -> **/containermanagerd.log.*

No files found for mobileInstall -> **/mobile_installation.log.*

No files found for restoreLog -> **/private/var/mobile/MobileSoftwareUpdate/restore.log

No files found for notes -> */NoteStore.sqlite*

No files found for notificationsXII -> *private/var/mobile/Library/UserNotifications*

No files found for notificationsDuet -> */DuetExpertCenter/streams/userNotificationEvents/local/*

No files found for notificationsDuet -> */userNotificationEvents/local/*

No files found for notificationsXI -> *PushStore*

No files found for reminders -> **/Reminders/Container_v1/Stores/*.sqlite*

No files found for safariFavicons -> */Containers/Data/Application/*/Library/Image Cache/Favicons/Favicons.db*

No files found for safariTabs -> **/Safari/BrowserState.db*

No files found for safariBookmarks -> **/Safari/Bookmarks.db*

No files found for safariWebsearch -> **/Safari/History.db*

No files found for safariRecentWebSearches -> **/Library/Preferences/com.apple.mobilesafari.plist

No files found for slack -> */var/mobile/Containers/Data/Application/*/Library/Application Support/Slack/*/Database/main_db*

No files found for queryPredictions -> **/query_predictions.db

No files found for textinputTyping -> */DES/Records/com.apple.TextInput.TypingDESPlugin/*.desdata

No files found for tikTok -> */Application/*/Library/Application Support/ChatFiles/*/db.sqlite*

No files found for tikTok -> *AwemeIM.db*

No files found for venmo -> *PrivateFeed

No files found for venmo -> *PublicFeed

No files found for venmo -> *FriendsFeed

No files found for viber -> **/com.viber/settings/Settings.data

No files found for viber -> **/com.viber/database/Contacts.data

No files found for viber -> **/Containers/Data/Application/*/Documents/Attachments/*.*

No files found for viber -> **/com.viber/ViberIcons/*.*

No files found for vippsContacts -> */Vipps.sqlite*

No files found for vipps -> */Vipps.sqlite*

No files found for voiceRecordings -> **/Recordings/*.composition/manifest.plist

No files found for voiceRecordings -> **/Recordings/*.m4a

No files found for voiceTriggers -> **/td/audio/*.json

No files found for voiceTriggers -> **/td/audio/*.wav

No files found for whatsappMessages -> */var/mobile/Containers/Shared/AppGroup/*/ChatStorage.sqlite*

No files found for whatsappMessages -> */var/mobile/Containers/Shared/AppGroup/*/Message/Media/*/*/*/*.*

No files found for whatsappContacts -> */var/mobile/Containers/Shared/AppGroup/*/ContactsV2.sqlite*

No files found for iCloudWifi -> **/com.apple.wifid.plist

No files found for applewifiplist -> **/com.apple.wifi.plist

No files found for applewifiplist -> **/com.apple.wifi-networks.plist.backup

No files found for applewifiplist -> **/com.apple.wifi.known-networks.plist

No files found for applewifiplist -> **/com.apple.wifi-private-mac-networks.plist

No files found for wifiNetworkStoreModel -> **/private/var/root/Library/Application Support/WiFiNetworkStoreModel.sqlite*

No files found for wiloc ->

Any idea to slve this?

Best!

Jonathan

**Comment by abrignoni** [comment]
Your source does not have the files the tool is looking for in order to parse them.

**Comment by JSulkin** [comment]
I made 2 backups, itunes and directly with finder...

The Itunes backup doenst found the files, and the finder backup says this:

(env) *****@iMac-de-Familia iLEAPP % python3 ileappGUI.py
Traceback (most recent call last):
  File "/Users/*****/Desktop/Herramientas/iLEAPP/ileappGUI.py", line 219, in <module>
    crunch_successful = ileapp.crunch_artifacts(
  File "/Users/*****/Desktop/Herramientas/iLEAPP/ileapp.py", line 146, in crunch_artifacts
    plugin.method([info_plist_path], out_params.report_folder_base, seeker, wrap_text)
UnboundLocalError: local variable 'plugin' referenced before assignment

Best!!!

**Comment by abrignoni** [comment]
1) itunes backups cannot be encrypted.
2) I don't know what a finder backup is.

**Comment by JSulkin** [comment]
El Backup del Finder me refiero a que esta hecho directo con el explorador de archivos de MAC, pero aun así al correrlo sin enviroment tiene un error:
Traceback (most recent call last):
  File "/Users/***/Desktop/Ileapp/iLEAPP/ileappgui.py", line 219, in <module>
    crunch_successful = ileapp.crunch_artifacts(
  File "/Users/***/Desktop/Ileapp/iLEAPP/ileapp.py", line 146, in crunch_artifacts
    plugin.method([info_plist_path], out_params.report_folder_base, seeker, wrap_text)
UnboundLocalError: local variable 'plugin' referenced before assignment

Hay una variable que no está definida aun...

Alexis, es espectacular tu trabajo.. muchas gracias por tu tiempo...

**Comment by abrignoni** [comment]
Pude recrear el problema con un backup de iTunes. Estoy verificando que está pasando...

**Comment by abrignoni** [comment]
Ya. Intenta con el backup de iTunes.

**Comment by JSulkin** [comment]
Listo!!!
Eres un genio!!!!

Muchas gracias y espero poder aportar algo al proyecto pronto..

Saludos!
