### ISSUE TITLE
sqlite3 error when searching for ProductBuildVersion 

### ISSUE THREAD

**Issue by hadar0x** [abrignoni/iLEAPP#4]
```
--------------------------------------------------------------------------------------
iLEAPP: iOS Logs, Events, and Preferences Parser
Objective: Triage iOS Full System Extractions.
By: Alexis Brignoni | @AlexisBrignoni | abrignoni.com
Artifact categories to parse: 38
File/Directory selected: /Volumes/davids_iphone

--------------------------------------------------------------------------------------


Mobile Installation Logs function executing
Logs processed: 2
Lines processed: 2171

Total apps: 326
Total installed apps: 326
Total uninstalled apps: 0
Total historical app reports: 326
Total system state events: 5
Mobile Installation Logs function completed.

Iconstate function executing
Screens: 2
Icons in bottom bar: 4
Iconstate function completed.

No files found for webclips -> *WebClips/*.webclip/*.

Lastbuild function executing
Traceback (most recent call last):
  File "./ileapp.py", line 101, in <module>
    globals()[key](filefound)
  File "/Users/hadar0x/Desktop/iLEAPP/ilapfuncs.py", line 2055, in lastbuild
    deviceinfoin(ordes, kas, vas, sources)
  File "/Users/hadar0x/Desktop/iLEAPP/ilapfuncs.py", line 4603, in deviceinfoin
    cursor.execute('INSERT INTO devinf (ord, ka, va, source)  VALUES(?,?,?,?)', datainsert)
sqlite3.InterfaceError: Error binding parameter 3 - probably unsupported type.
```

**Comment by hadar0x** [comment]
ah i think i found it...
it's actually not the parameter 3... it's the first parameter (ord)
in the deviceinfo function, you execute the following:
`cursor.execute('CREATE TABLE devinf (ord TEXT, ka TEXT, va TEXT, source TEXT)')`
but then in the lastbuild function, you pass an integer:
	```
	if key == 'ProductBuildVersion':
			ordes = 8
			kas = 'Build Version'
			vas = val
			sources = filefound[0]
			deviceinfoin(ordes, kas, vas, sources)
```

**Comment by hadar0x** [comment]
ok, i printed the type of 'sources', and it's  `<class 'pathlib.PosixPath'>`
however, when the table is created, the source type is set to TEXT
`cursor.execute('CREATE TABLE devinf (ord TEXT, ka TEXT, va TEXT, source TEXT)')`

When I use str(sources), everything seems to be working fine :)

**Comment by abrignoni** [comment]
What version of python are you running? I can change the type right before the insert if needed in deviceinfoin(). I just wonder why can't I replicate the error. Thoughts?

**Comment by hadar0x** [comment]
Python 3.7.0

**Comment by abrignoni** [comment]
Python 3.7.4

Installed Python 3.7.0 on another computer. Was not able to replicate the error. :-(

**Comment by hadar0x** [comment]
`python3 -c 'import sqlite3; print(sqlite3.version)' `
2.6.0

Yours?

**Comment by abrignoni** [comment]
Yes. You are correct. I was able to replicate. My attempt at aggregating the device info for the report broke the FS parse. Your fix was also spot on. Since the path object is just for display purposes in the report it does not interfere with any other functionality.

I made the change you suggested in deviceinfoin() and it worked for all extraction types. Thank you so much!!!!
