### ISSUE TITLE
tkinter required

### ISSUE THREAD

**Issue by fftux** [abrignoni/iLEAPP#48]
Hi!  Was helping a friend get this running and I noticed that the GUI would not run on my machine (Fedora 30).  I was able to discern from the error that I did not have tkinter installed.  I was able to grab that and get things working, but I thought that others may find it helpful to have this called out in the README.

I wasn't able to find tkinter via pip, or I would have just submitted a PR with an updated requirements.txt.

Cheers!

**Comment by ydkhatri** [comment]
Yes, that is correct. I just added a note about it in the README.md file on the homepage.
