### ISSUE TITLE
Several plugins depend on lastBuild.py plugin

### ISSUE THREAD

**Issue by ydkhatri** [abrignoni/iLEAPP#51]
With the GUI allowing selection of modules, a user could select plugins that have the dependency and not select lastBuild.py, which results in exceptions.
Either the gui code can be changed to always select this plugin (regardless of user input) , or remove it from the plugins altogether and always run it.

**Comment by abrignoni** [comment]
Some thoughts:
1) How about changing the artifacts to take into account that if an iOS version number is zero (the default when lastbuild.py is not selected or if there is an error) the artifact should just output to the log the lack of iOS version and move to the next artifact gracefully. 

2) If option 1 is not a good idea then, like you said, let's make lastBuild.py mandatory. My preference would be to make it always selected but if that is to much of a hassle then we can always run it without it showing on selection of artifacts screen portion.

I you like I can start tinkering with the code right after we decide what to do.

**Comment by ydkhatri** [comment]
I am leaning towards 2. That is quick and easy. I can fix the code later today.

**Comment by ydkhatri** [comment]
#52 implements this
