### ISSUE TITLE
MS Teams

### ISSUE THREAD

**Issue by tokyohelsinki** [abrignoni/iLEAPP#515]
Hi,
getting "argument of type 'NoneType' is not iterable" errors from teams.py artifact when running the script and no data from the Teams DB is added to the report.

**Comment by abrignoni** [comment]
Is there any teams data in the extraction? Please advise. If not that might
mean the grep at the bottom of the artifact picked up a file that is named
as the teams DB but is not.

One possible solution would be for us to narrow down the grep a little
better.

**Comment by JamesHabben** [comment]
@tokyohelsinki can you let us know?

**Comment by JamesHabben** [comment]
closing as we dont have any additional information. we can add some additional error checking when updating this module in the output updates.
