### ISSUE TITLE
iLEAPP GUI Reference to ALEAPP

### ISSUE THREAD

**Issue by JamesHabben** [abrignoni/iLEAPP#573]
I haven't dug into the GUI side much, so unsure if this is an issue. Saw it while going through with consistency updates. Are these supposed to reference A stuff?

https://github.com/abrignoni/iLEAPP/blob/6ff56d16a4a635693fa3ec3744a0b4d708fae8a1/ileappGUI.py#L161

https://github.com/abrignoni/iLEAPP/blob/6ff56d16a4a635693fa3ec3744a0b4d708fae8a1/ileappGUI.py#L174

https://github.com/abrignoni/iLEAPP/blob/6ff56d16a4a635693fa3ec3744a0b4d708fae8a1/ileappGUI.py#L195-L196

**Comment by abrignoni** [comment]
![Screenshot 2023-10-18 at 1 18 01 PM](https://github.com/abrignoni/iLEAPP/assets/28718987/32b044f4-31e1-4e62-b44f-82aa440b3984)
Any idea why this icon is not showing up? it should...

**Comment by JamesHabben** [comment]
just caught that bug on a few entries. the lookup function looks for lower `default` and i mistakenly entered several as upper `DEFAULT`. have a patch going for that right now.

![image](https://github.com/abrignoni/iLEAPP/assets/6327329/fe9fdd87-9cfc-43dd-88eb-7e173f3d86c3)

**Comment by JamesHabben** [comment]
sent a PR to correct that mistake, and sending PRs to the others as well. otherwise closing this.
