### ISSUE TITLE
SplashBoard Error

### ISSUE THREAD

**Issue by koosh7** [abrignoni/iLEAPP#59]
I was using iLEAPP command line and .exe and receiving this message.. Wondered if it was an error...
ios 13.3.  I also received the same error when i was running a ios 13.4 image.

![iLEAPP13 3](https://user-images.githubusercontent.com/7409072/88701665-f080c500-d0cf-11ea-86d6-f27a9ad0b167.JPG)

**Comment by ydkhatri** [comment]
I think I know what the issue is, will try to fix it later tonight.

**Comment by ydkhatri** [comment]
Was the input a zip file?

**Comment by ydkhatri** [comment]
OK, I fixed the issue for zip files now #60. 
Perhaps a little later, Alex can create and upload a new exe with the changes.

**Comment by abrignoni** [comment]
On it. 👍

**Comment by abrignoni** [comment]
Done.

https://github.com/abrignoni/iLEAPP/releases/tag/1.3.1

**Comment by koosh7** [comment]
thanks guys.... just re-ran the image without issue...
