### ISSUE TITLE
ilap_artifacts.py

### ISSUE THREAD

**Issue by Johann-PLW** [abrignoni/iLEAPP#611]
@abrignoni 
The ilap_artifacts.py file seems no longer to be used anymore.
I did not find any reference to it and iLEAPP is still working after removing it.

The same observation for DLEAPP, RLEAPP and VLEAPP.

On the other hand, this file is not present in ALEAPP and is still required in WLEAPP.

Should we remove it from iLEAPP, DLEAPP, RLEAPP and VLEAPP?

**Comment by abrignoni** [comment]
Yes. They file used to be what we used to grep the files per artifact. It
is not needed anymore.
