### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by abrignoni** [abrignoni/iLEAPP#63]
This section is to receive feature requests from the community. Please leave them as a comment below.

**Comment by jim-stew** [comment]
Request the ability to create date range of artifacts before parsing starts.

**Comment by golikja** [comment]
Request to be able to retrieve TikTok comments

**Comment by upintheairsheep** [comment]
> Request to be able to retrieve TikTok comments

This is from the cloud. Use oxygen cloud extractor

**Comment by upintheairsheep** [comment]
Recent emojis from the iPhone keyboard

**Comment by abrignoni** [comment]
Closing these request threads. They became long "parse every app ever invented without the requester providing any coding support or sample data to assist" threads. Totally useless.
