### ISSUE TITLE
Column order issue with Sync.db parser

### ISSUE THREAD

**Issue by Johann-PLW** [abrignoni/iLEAPP#639]
Which version of iOS did you use to develop the Sync.db parser?
With Josh's iOS 15 public image:
<img width="1407" alt="image" src="https://github.com/abrignoni/iLEAPP/assets/27498476/4bc23337-4083-4fcf-875c-25059998bdb4">

With an another iOS 16.2 dataset :
<img width="1352" alt="image" src="https://github.com/abrignoni/iLEAPP/assets/27498476/8cab19d2-de2a-4d9b-9398-4c890bc482ef">

The order of columns seems to be different than yours

**Comment by abrignoni** [comment]
Josh's iOS 15. That is an easy fix. I just need to reference them by name,
assuming the names are the same, instead of by order.

Can you send me the names of the fields in iOS 16?

**Comment by Johann-PLW** [comment]
Sure.
Here you are
<img width="703" alt="image" src="https://github.com/abrignoni/iLEAPP/assets/27498476/773ecf9c-d936-433e-aac0-ce111c853b83">

**Comment by abrignoni** [comment]
Fixed by #640
