### ISSUE TITLE
GUI Plugin Scroll

### ISSUE THREAD

**Issue by JamesHabben** [abrignoni/iLEAPP#642]
I noticed on my windows computer using the compiled release GUI exe that the plugin box won't scroll with my mouse wheel unless it is over the scroll bar itself. The scroll doesn't respond to my mouse scroll if my mouse cursor is over the list of plugins.

**Comment by Johann-PLW** [comment]
This is not something only related to the compiled GUI release on Windows platforms.
I have the same behavior on my Mac. It is a known bug of PySimpleGUI.
iLEAPP forces version 4.16.0 to be installed (PySimpleGUI==4.16.0 in requirements.txt file)
I have upgraded to latest version 4.60.5 and now I am able to scroll when my cursor is inside the plugin box.
But some changes occurred in the GUI
PySimpleGUI v4.16.0
<img width="1023" alt="image" src="https://github.com/abrignoni/iLEAPP/assets/27498476/bc7277f3-bfd4-4f89-88c0-17608ed5a017">

PySimpleGUI v4.60.5
<img width="996" alt="image" src="https://github.com/abrignoni/iLEAPP/assets/27498476/7205bcd6-0ef0-473d-9c71-ffec3949587a">

If we use v4.59.0, scroll works as expected and GUI stays the same:
<img width="1003" alt="image" src="https://github.com/abrignoni/iLEAPP/assets/27498476/818aca65-dde6-405c-9a6b-521f7796b27e">

**Comment by JamesHabben** [comment]
Oh, good find @Johann-PLW. I think the latest with the color changes look better as a proper UI.

**Comment by Johann-PLW** [comment]
And I was able to increase the size of output log box.
<img width="952" alt="image" src="https://github.com/abrignoni/iLEAPP/assets/27498476/9700d63f-d14f-4080-bf59-74fa0f8dcd20">

**Comment by stark4n6** [comment]
The newer version of PySimpleGUI looks slick, does it break anything you've found? I wonder if it's just a simple update

**Comment by Johann-PLW** [comment]
Everything works fine except:
- After selecting input file/folder and output folder, the plugin window loses the focus so we have to click inside the main window once before to be able to select/unselect modules
- Some adjustments in code to fix this PEP8 warning
<img width="546" alt="image" src="https://github.com/abrignoni/iLEAPP/assets/27498476/b3386371-ed23-4365-9a93-74d729d7058b">

**Comment by Johann-PLW** [comment]
I've just run a few more tests by :
- adjusting the size of output logs
- replacing FindElement with windows[key] and window.find_element as suggested in PEP8 warnings.
Just four lines of code updated in ileappGUI.py file and it works perfectly both with PySimpleGUI 4.0.16 (actual one used by iLEAPP) and the new 4.60.5 version.
So I think I can push this little modifications then we can decide whether we want to use the latest version of PySimpleGUI just by updating requirements.txt file or stay with 4.0.16
In the end, no action required by the user.

**Comment by abrignoni** [comment]
Based on your work I think we should move to the new version of
PYsimpleGUI.

Thank you!
