### ISSUE TITLE
Mac and Linux builds

### ISSUE THREAD

**Issue by grrrrr** [abrignoni/iLEAPP#677]
This is a little a request for  both iLeapp and aLeapp.

Would it be feasible to include binaries for both Linux and Mac in the build pipeline  at same time when you build for Windows releases?

**Comment by Johann-PLW** [comment]
Hello @grrrrr,
iLEAPP v1.19.1 has just been released and also includes binaries for both Mac Intel and Apple Silicon.
I will have a look to try to also generate linux binaries for the next release.

**Comment by grrrrr** [comment]
Merci @Johann-PLW

**Comment by Johann-PLW** [comment]
Hello @grrrrr,
Linux binaries are now available for Ubuntu 22.04 and above.

**Comment by grrrrr** [comment]
tested and working perfectly. Thank you!
