### ISSUE TITLE
Text input session #737

### ISSUE THREAD

**Issue by cf-eglendye** [abrignoni/iLEAPP#804]
I just wanted to let you know that during this commit, the update now subtracts cocoa time offset. from running this module my timestamps are now incorrect. Manual timestamp decoding is 2022-08-30 19:18:22 for the first Viber input session. Maybe this needs looking at again :)

![image](https://github.com/user-attachments/assets/0230fdce-244c-40d2-9414-3c7cc280fd64)

**Comment by stark4n6** [comment]
@snoop168 can you look at this further?
