### ISSUE TITLE
Need to consolidate 2 wifi plugins

### ISSUE THREAD

**Issue by ydkhatri** [abrignoni/iLEAPP#88]
There is 
`            'appleWifiPlist':('Wireless Networks', '**/SystemConfiguration/com.apple.wifi.plist'),`
and
`            'wifi':('Wifi Connections', '**/com.apple.wifi.plist'),`

![image](https://user-images.githubusercontent.com/13247440/93919031-324a7800-fcdb-11ea-81aa-44dff8348171.png)

Both provide similar data, need to be merged.

**Comment by abrignoni** [comment]
Whoops! Will work on it tonight. 👍

**Comment by threeplanetssoftware** [comment]
I don't think this got "fixed", but `appleWifiPlist` is throwing errors for phones that don't have any stored wireless networks, so I'm cleaning that script up. I'm adding in support for networks scanned with a private MAC address (newer feature, i think?) that has many similar fields.
