### ISSUE TITLE
Inserting list or dict values in lava_output SQLite database

### ISSUE THREAD

**Issue by Johann-PLW** [abrignoni/iLEAPP#916]
Some plist files contain Arrays (List) or dictionaries datatypes as values.
This datatype is not supported by the lava_insert_sqlite_data function in lavafuncs.py file.

**Comment by JamesHabben** [comment]
@Johann-PLW can you share which module and artifact you are hitting this with?

**Comment by Johann-PLW** [comment]
I have identified two modules at the moment:
- imeiImsi.py
- findMyItems.py

**Comment by Johann-PLW** [comment]
`lavafuncs.py` was updated to detect values of type dict or list and store them in `_lava_artifacts.db` as JSON.

**Comment by JamesHabben** [comment]
Are we solved on this then or are you planning for more work? We can open an issue in lava for the json display.

**Comment by Johann-PLW** [comment]
I think this issue is solved for the Python part and we can open an issue for lava.
